<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <CodeAnalysisRuleSet>..\..\Analyzers.ruleset</CodeAnalysisRuleSet>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>61a7b799-0c15-4961-a256-98098694b10f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Template.ApiServer.Host\Template.ApiServer.Host.csproj" />
  </ItemGroup>

</Project>
